default: &default
  adapter: mysql2
  encoding: utf8
  username: admin
  password: "@Trung180898"
  host: localhost
  port: 3306

development:
  <<: *default
  database: sample_app

test:
  <<: *default
  database: test_db_name

production:
  <<: *default
  database: production_db_name